### ISSUE TITLE
iOS 14.1

### ISSUE THREAD

**Issue by m1entus** [lemon4ex/Reveal2Loader#10]
Hey, i know that it is written that you support iOS13, but is it a change to support iOS 14 ? - Currently it is installing but application is not showing up, maybe will be good time to update to support newest reveal and iOS 14 ?

**Comment by lemon4ex** [comment]
The v1.0.4 version has been tested on iPhone 11 pro 14.2 and iPhone 6s 14.5.
If you need to support the latest reveal, you can directly replace Package/Library/Frameworks/RevealServer.framework and it should work normally.
