### ISSUE TITLE
iPad 13.6.1 设置无法显示内容

### ISSUE THREAD

**Issue by NasserGo** [lemon4ex/Reveal2Loader#16]
已经安装上了，但是设置中点开Reveal，显示：There appears to be an error with these preferences!
设备：iPad Pro 12.9 第二代
越狱：已越狱
系统版本：13.6.1
盼回复

**Comment by lemon4ex** [comment]
越狱工具是一款？如果是coolstar团队开发的越狱工具，用的libhooker基板，这个问题应该是已知问题，应该是依赖库(AppList等)本身的兼容问题

**Comment by NasserGo** [comment]
完美解决，十分感谢。

**Comment by oahgnehzoul** [comment]
你好，请问下这个依赖库的兼容问题具体是怎么解决

**Comment by LionWY** [comment]
+ 1
