### ISSUE TITLE
iOS 14.8.1 iPhoneX Taurine+Sileo越狱

### ISSUE THREAD

**Issue by oahgnehzoul** [lemon4ex/Reveal2Loader#19]
越狱后安装了Reveal2Loader，进到设置页面，提示“There appears to be an error with these preferences!”       

请教下这个问题如何解决，下面这个issue未找到具体的解决步骤

 越狱工具是一款？如果是coolstar团队开发的越狱工具，用的libhooker基板，这个问题应该是已知问题，应该是依赖库(AppList等)本身的兼容问题

_Originally posted by @lemon4ex in https://github.com/lemon4ex/Reveal2Loader/issues/16#issuecomment-1092325033_

**Comment by DeftMKJ** [comment]
> 越狱后安装了Reveal2Loader，进到设置页面，提示“There appears to be an error with these preferences!”
> 
> 请教下这个问题如何解决，下面这个issue未找到具体的解决步骤
> 
> 越狱工具是一款？如果是coolstar团队开发的越狱工具，用的libhooker基板，这个问题应该是已知问题，应该是依赖库(AppList等)本身的兼容问题
> 
> _Originally posted by @lemon4ex in [#16 (comment)](https://github.com/lemon4ex/Reveal2Loader/issues/16#issuecomment-1092325033)_

https://github.com/DeftMKJ/MKJRevealLoaderX

**Comment by LionWY** [comment]
+ 1，怎么解决？
