### ISSUE TITLE
请问一下怎么装到手机上呢

### ISSUE THREAD

**Issue by swsdyg** [lemon4ex/Reveal2Loader#2]
你好，第一次研究越狱，越狱的手机版本是ios 11.4，发现通过cydia下载的Reveal2Loader不好用了，然后找到了这里，想请教一下我应该怎样把您的修改安装到越狱机上，目前我只知道通过cydia安装，谢谢🙏

**Comment by lemon4ex** [comment]
方法有很多，百度一下你就知道。

**Comment by ljsenjj** [comment]
大神，请问百度什么？关键字是什么？

**Comment by ixzk** [comment]
刚开始笑话了一下上面这位，现在要哭了，作为一个iOS开发者，这玩意儿也不知道怎么装😂， 请教楼上两位怎么装上的
