### ISSUE TITLE
您好 这个可以通过Cydia安装么

### ISSUE THREAD

**Issue by SummerHF** [lemon4ex/Reveal2Loader#8]
具体如何使用咧 还请赐教

**Comment by lemon4ex** [comment]
可以 不过安装之前还需要安装其他依赖库，具体谷歌或者看原作者的仓库说明。

**Comment by SummerHF** [comment]
```
# inject into trust cache
inject `which Clutch`
```
还想讨教下使用inject指令为什么命令行会报错咧? -sh: inject: command not found , 或者说这是哪一个工具啊 网上没找到
